customer: ""

aml_experiment_details:
  compute_name: cheap-cpu-andrea
  env_name: oor-environment
  env_version: 47
  src_dir: "."

azure_iot:
  hostname: "iothub-oor-ont-weu-itr-01.azure-devices.net"
  device_id: "test-diana"
  shared_access_key: "{SHARED_ACCESS_KEY_IOT}"

convert_dataset:
  input_old_datastore: "old_datastore"
  output_new_datastore: "new_datastore"
  face_width: 1024

convert_annotations:
  input_datastore_name: annotations_conversion_old
  output_datastore_name: annotations_conversion_new
  final_datastore_name: converted_data_240729_240805
  categories_file: categories.json
  separate_labels: True
  label_folder: new_data_240729_240805/labels

data_delivery_pipeline:
  images_path: "/raw_frames"
  detections_path: ""
  frame_metadata_path: "/raw_videos"

data_sampling:
  inputs:
    datastore: "oor_velotech"
    rel_path: "frames/20240329-141802"
    frame_metadata_rel_path: "frames/metadata"
    decos_rel_path: "decos"
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames/sample"
  n_frames: 1500
  sampling_weight: 1.0
  decos_radius: 30

distortion_correction:
  cx: 0.509
  cy: 0.488
  k1: -0.241
  k2: 0.106

frame_extraction:
  inputs:
    datastore: "oor_velotech"
    rel_path: ""
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames"
    metadata_rel_path: "frames/metadata"
  log_dir: "logs"
  exclude_dirs: ["checkboard", "frames", "decos"]  # Do not check for MP4 in these dirs
  exclude_files: ["D17M02Y2024-H20M50S55"]  # Metadata for this file is invalid
  fps: 1

training_pipeline:
  model_parameters:
    img_size: 1280
    batch: 0.85
    epochs: 500
    patience: 100
    n_classes: 5
    cos_lr: True
    dropout: 0.0
    seed: 0
    box: 7.5
    cls: 0.5
    dfl: 1.5
    name_classes: ["person", "license plate", "container", "mobile toilet", "scaffolding"]
    rect: False
  inputs:
    datastore_path: "dataset_oor_v2_0"
    training_data_rel_path: "processed-dataset-oor-v2-0"
    model_weights_rel_path: "model"
    model_name: "best_yolov8m_coco_290524_old_oor_nc_5.pt"
    wandb_api_key: "3913776b1d82ae9f4f08090917114a0ad61ecfcf"
    wandb_mode: "online"
  outputs:
    project_datastore_path: "dataset_oor_v2_0"
    project_rel_path: "model"

sweep_pipeline:
  model_parameters:
    img_size: 1280
    batch: 0.85
    epochs: 100
    patience: 100
    n_classes: 5
    name_classes: ["person", "license plate", "container", "mobile toilet", "scaffolding"]
    rect: False
  sweep_trials: 30
  inputs:
    datastore_path: "dataset_oor_v2_0"
    training_data_rel_path: "processed-dataset-oor-v2-0"
    model_weights_rel_path: "model"
    model_name: "best_yolov8m_coco_290524_old_oor_nc_5.pt"
    wandb_api_key: "3913776b1d82ae9f4f08090917114a0ad61ecfcf"
    wandb_mode: "online"
    sweep_config: "sweep_config.json" # needs to be in the same directory as model_weights_rel_path
  outputs:
    project_datastore_path: "dataset_oor_v2_0"
    project_rel_path: "model"

logging:
  loglevel_own: DEBUG  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte", "convert_annotations"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: ""
