customer: ""

aml_experiment_details:
  compute_name: oor-testing
  env_name: oor-environment
  env_version: 37
  src_dir: "."

inference_pipeline:
  detection_params:
    batch_size: 1
    img_size: 1280
    conf: 0.4
    save_img_flag: False
    save_txt_flag: False
    save_conf_flag: False
  inputs:
    datastore_path: "first_official_training_dataset_oor"
    inference_data_rel_path: "processed-merged-batches-first-official-training-dataset-oor/images/"
    model_weights_rel_path: "model"
    model_name: "yolov8m_1280_oor_v2_best.pt"
  outputs:
    project_rel_path: "inference/logging_test"
  target_classes: [2, 3, 4]
  sensitive_classes: [0, 1]
  output_image_size: [1280, 720]
  save_detection_images: True
  save_detection_labels: True
  defisheye_flag: True
  defisheye_params:
    camera_matrix: [[2028, 0, 1954.1], [0, 2029.6, 1055.1], [ 0, 0, 1]]
    distortion_params: [[-0.24083, 0.10647, 0.00083113, 0.0001802, -0.025874]]
    input_image_size: [3840, 2160]

logging:
  loglevel_own: DEBUG  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte", "run_inference"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: DEBUG
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: ""
