customer: ""

aml_experiment_details:
  compute_name: cpu-daan-D13v2
  env_name: oor-test-environment
  env_version: 3


azure_iot:
  hostname: ""
  device_id: ""
  shared_access_key: ""


distortion_correction:
  cx: 0.509
  cy: 0.488
  k1: -0.241
  k2: 0.106


frame_extraction:
  inputs:
    datastore: "oor_velotech"
    rel_path: ""
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames"
    metadata_rel_path: "frames/metadata"
  log_dir: "logs"
  exclude_dirs: ["checkboard", "frames", "decos"]
  exclude_files: ["D17M02Y2024-H20M50S55"]
  fps: 1


logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: INFO
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
