azure_iot:
  hostname: "iothub-oor-ont-weu-itr-01.azure-devices.net"
  device_id: "test-diana"
  shared_access_key: "{SHARED_ACCESS_KEY_IOT}"

data_delivery_pipeline:
  images_path: "/raw_frames"
  detections_path: ""
  metadata_path: ""

logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: INFO
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
