databricks_pipelines:
    Ontwikkel:
      catalog: "dpcv_dev"
      schema: "oor"
      storage_account_root_path: "abfss://landingzone@stlandingdpcvontweu01.dfs.core.windows.net"
      device_id: "Luna"
      ckpt_frames_relative_path: checkpoints/_checkpoint_frames
      ckpt_detections_relative_path: checkpoints/_checkpoint_detections
      vuln_bridges_relative_path: "vuln_bridges.geojson"
      reference_database:
        host: "dev-bbn1-01-dbhost.postgres.database.azure.com"
        name: "mdbdataservices"
      signalen:  
        access_token_url: "https://acc.iam.amsterdam.nl/auth/realms/datapunt-ad-acc/protocol/openid-connect/token"
        base_url: "https://api.acc.meldingen.amsterdam.nl/signals/v1/private/signals"
        client_id: "sia-cvt"
        client_secret_name: "sia-password-acc"
      azure_tenant_id: "72fca1b1-2c2e-4376-a445-294d80196804"
      object_classes:
        # available:
        #   2: "container"
        #   3: "mobiel toilet"
        #   4: "steiger"
        active:
          2: "container"
          # 3: "mobiel toilet"
          # 4: "steiger"
        permit_mapping:
          2: ["puinbak", "container", "keet", "cabin"]
          3: ["toilet"]  # TODO: check with BOR if more are relevant
          4: ["steiger"]  # TODO: check with BOR if more are relevant
    Productie: 
      catalog: "dpcv_prd"
      schema: "oor"
      storage_account_root_path: "abfss://landingzone@stlandingdpcvprdweu01.dfs.core.windows.net"
      device_id: "Luna"
      ckpt_frames_relative_path: checkpoints/_checkpoint_frames
      ckpt_detections_relative_path: checkpoints/_checkpoint_detections
      vuln_bridges_relative_path: "vuln_bridges.geojson"
      reference_database:
        host: "prd-bbn1-01-dbhost.postgres.database.azure.com"
        name: "mdbdataservices"
      signalen:  
        access_token_url: "https://iam.amsterdam.nl/auth/realms/datapunt-ad/protocol/openid-connect/token"
        base_url: "https://api.meldingen.amsterdam.nl/signals/v1/private/signals"
        client_id: "sia-cvt"
        client_secret_name: "sia-password-prd"
      azure_tenant_id: "72fca1b1-2c2e-4376-a445-294d80196804"
      object_classes:
        # available:
        #   2: "container"
        #   3: "mobiel toilet"
        #   4: "steiger"
        active:
          2: "container"
          # 3: "mobiel toilet"
          # 4: "steiger"
        permit_mapping:
          2: ["puinbak", "container", "keet", "cabin"]
          3: ["toilet"]  # TODO: check with BOR if more are relevant
          4: ["steiger"]  # TODO: check with BOR if more are relevant
