customer: ""

aml_experiment_details:
  compute_name: cpu-daan-D13v2
  env_name: oor-test-environment
  env_version: 3


azure_iot:
  hostname: ""
  device_id: ""
  shared_access_key: ""


data_sampling:
  inputs:
    datastore: "oor_velotech"
    rel_path: "frames/20240329-141802"
    metadata_rel_path: "frames/metadata"
    decos_rel_path: "decos"
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames/sample"
  n_frames: 1500
  sampling_weight: 1.0
  decos_buffer: 30


distortion_correction:
  cx: 0.509
  cy: 0.488
  k1: -0.241
  k2: 0.106


frame_extraction:
  inputs:
    datastore: "oor_velotech"
    rel_path: ""
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames"
  log_dir: "logs"
  exclude_dirs: ["checkboard", "frames"]
  fps: 1


logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
