customer: ""

aml_experiment_details:
  compute_name: cpu-blurring-model2
  env_name: oor-environment
  env_version: 2
  src_dir: "."

azure_iot:
  hostname: "iothub-oor-ont-weu-itr-01.azure-devices.net"
  device_id: "test-diana"
  shared_access_key: "{SHARED_ACCESS_KEY_IOT}"

data_delivery_pipeline:
  images_path: "/raw_frames"
  detections_path: ""
  metadata_path: ""

convert_dataset:
  input_old_datastore: "old_datastore"
  output_new_datastore: "new_datastore"
  face_width: 1024

convert_annotations:
  input_datastore_name: annotations_conversion_old
  output_datastore_name: annotations_conversion_new
  final_datastore_name: converted_new_dataset_oor
  categories_file: categories.json
  separate_labels: True
  label_folder: prelabeling_new_dataset_oor/labels

distortion_correction:
  cx: 0.509
  cy: 0.488
  k1: -0.241
  k2: 0.106

frame_extraction:
  inputs:
    datastore: "oor_velotech"
    rel_path: ""
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames"
    metadata_rel_path: "frames/metadata"
  log_dir: "logs"
  exclude_dirs: ["checkboard", "frames", "decos"]  # Do not check for MP4 in these dirs
  exclude_files: ["D17M02Y2024-H20M50S55"]  # Metadata for this file is invalid
  fps: 1

logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte", "convert_annotations"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "APPLICATION_INSIGHTS_CONNECTION_STRING"
