customer: ""

aml_experiment_details:
  compute_name: oor-testing
  env_name: oor-environment
  env_version: 51
  src_dir: "."

distortion_correction:
  defisheye_params:
    camera_matrix: [[2028, 0, 1954.1], [0, 2029.6, 1055.1], [ 0, 0, 1]]
    distortion_params: [[-0.24083, 0.10647, 0.00083113, 0.0001802, -0.025874]]
    input_image_size: [3840, 2160]

inference_pipeline:
  model_params:
    batch_size: 1
    img_size: 1280
    conf: 0.3
  inputs:
    datastore_path: "inference_test"
    inference_data_rel_path: "datasets/demo_images"
    model_weights_rel_path: "model_weights"
    model_name: "yolov8m_1280_v2.2_curious_hill_12.pt"
  outputs:
    datastore_path: "inference_test"  # empty string "" means same as input datastore
    output_rel_path: "inference/demo_images/test3/"
    detections_subfolder: ""
    labels_subfolder: ""
  target_classes: [2, 3, 4]
  sensitive_classes: [0, 1]
  target_classes_conf: 0.7  # null means conf is taken from model_params
  sensitive_classes_conf: null  # null means conf is taken from model_params
  output_image_size: [1280, 720]  # null means keep original size
  save_detection_images: True
  save_detection_labels: True
  defisheye_flag: False

logging:
  loglevel_own: DEBUG  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte", "inference_pipeline"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: DEBUG
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: ""
