customer: ""

aml_experiment_details:
  compute_name: cpu-blurring-model2
  env_name: oor-environment
  env_version: 2
  src_dir: "."

azure_iot:
  hostname: ""
  device_id: ""
  shared_access_key: ""

convert_dataset:
  face_width: 1024

logging:
  loglevel_own: INFO  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte", "convert_annotation"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: INFO
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "APPLICATION_INSIGHTS_CONNECTION_STRING"
