customer: ""

aml_experiment_details:
  compute_name: oor-testing
  env_name: oor-environment
  env_version: 25
  src_dir: "."

azure_iot:
  hostname: "iothub-oor-ont-weu-itr-01.azure-devices.net"
  device_id: "test-diana"
  shared_access_key: "{SHARED_ACCESS_KEY_IOT}"

convert_dataset:
  input_old_datastore: "old_datastore"
  output_new_datastore: "new_datastore"
  face_width: 1024

convert_annotations:
  input_datastore_name: annotations_conversion_old
  output_datastore_name: annotations_conversion_new
  final_datastore_name: converted_new_dataset_oor
  categories_file: categories.json
  separate_labels: True
  label_folder: prelabeling_new_dataset_oor/labels

data_delivery_pipeline:
  detections_path: "/detections"
  metadata_path: "/temp_metadata"
  ml_model_id: "{ML_MODEL_ID}"
  project_version: "{PROJECT_VERSION}"

detection_pipeline:
  images_path: "/raw_frames"
  detections_path: "/detections"
  inference_params:
    img_size: 1920
    conf: 0.4
    save_img_flag: False
    save_txt_flag: False
    save_conf_flag: False
  model_name: "yolov8s_coco_nc_5_best.pt"
  pretrained_model_path: "model_artifacts"
  defisheye_flag: False
  defisheye_params:
    camera_matrix: [[2028, 0, 1954.1], [0, 2029.6, 1055.1], [ 0, 0, 1]]
    distortion_params: [[-0.24083, 0.10647, 0.00083113, 0.0001802, -0.025874]]
    input_image_size: [3840, 2160]
  target_classes: [2]
  sensitive_classes: [0,1]
  output_image_size: [1920, 1080]

data_sampling:
  inputs:
    datastore: "oor_velotech"
    rel_path: "frames/20240329-141802"
    frame_metadata_rel_path: "frames/metadata"
    decos_rel_path: "decos"
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames/sample"
  n_frames: 1500
  sampling_weight: 1.0
  decos_radius: 30

distortion_correction:
  cx: 0.509
  cy: 0.488
  k1: -0.241
  k2: 0.106

frame_extraction:
  inputs:
    datastore: "oor_velotech"
    rel_path: ""
  outputs:
    datastore: "oor_velotech"
    rel_path: "frames"
    metadata_rel_path: "frames/metadata"
  log_dir: "logs"
  exclude_dirs: ["checkboard", "frames", "decos"]  # Do not check for MP4 in these dirs
  exclude_files: ["D17M02Y2024-H20M50S55"]  # Metadata for this file is invalid
  fps: 1

training_pipeline:
  model_parameters:
    img_size: 1024
    batch: -1
    epochs: 100
    patience: 25
    n_classes: 3
    name_classes: ["person", "license plate", "container"]
  inputs:
    datastore_path: "first_training_dataset_oor"
    training_data_rel_path: "first-training-dataset-oor"
    model_weights_rel_path: "model"
    model_name: "yolov8m.pt"
  outputs:
    project_datastore_path: "first_training_dataset_oor"
    project_rel_path: "model"

logging:
  loglevel_own: DEBUG  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "objectherkenning_openbare_ruimte", "convert_annotations",
                 "performance_monitoring", "detection_pipeline", "data_delivery_pipeline"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "{AI_INSTRUMENTATION_KEY}"
  luna_logs_dir: "/cvt_logs"
