[tool.poetry]
name = "objectherkenning_openbare_ruimte"
version = "0.1.0"
description = "Objectherkenning Openbare Ruimte is a project about recognising objects from public space images."
authors = [
    "Sebastian Davrieux <s.davrieux@amsterdam.nl>",
    "Diana Epureanu <d.epureanu@amsterdam.nl>",
    "Andrea Lombardo <a.lombardo@amsterdam.nl>"
]

[tool.poetry.dependencies]
python = "~3.8"
pre-commit = {version = "^3.2.0", source = "PyPI"}
aml_interface = { git = "https://github.com/Computer-Vision-Team-Amsterdam/AML-Interface.git",  tag = "v1.0.0" }
cvtoolkit = { git = "https://github.com/Computer-Vision-Team-Amsterdam/CVToolkit.git",  tag = "v1.0.2" }
pydantic = {version = "^1.8.2", source = "PyPI"}
azure-iot-device = {version = "^2.13.0", source = "PyPI"}
azure-storage-blob = "^12.19.0"
mldesigner = {version = "^0.1.0-beta.9", source = "PyPI"}
numpy = {version = "^1.24.2", source = "PyPI"}
py360convert-modified = {version = "^1.0.1", source = "PyPI"}
opencv-python = {version = "^4.8.0.74", source = "PyPI"}

[tool.poetry.dev-dependencies]

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
