[tool.poetry]
name = "objectherkenning_openbare_ruimte"
version = "0.1.0"
description = "Objectherkenning Openbare Ruimte is a project about recognising objects from public space images."
authors = [
    "Sebastian Davrieux <s.davrieux@amsterdam.nl>",
    "Diana Epureanu <d.epureanu@amsterdam.nl>",
    "Andrea Lombardo <a.lombardo@amsterdam.nl>"
]

[tool.poetry.dependencies]
python = "~3.8"
pre-commit = {version = "^3.2.0", source = "PyPI"}
cvtoolkit = { git = "https://github.com/Computer-Vision-Team-Amsterdam/CVToolkit.git",  tag = "v1.0.3" }
pydantic = {version = "^1.8.2", source = "PyPI"}
azure-iot-device = {version = "^2.13.0", source = "PyPI"}
azure-storage-blob = "^12.19.0"

[tool.poetry.dev-dependencies]
pytest = {version = "^7.0.1", source = "PyPI" }
pytest-cov = {version = "^4.0.0", source = "PyPI" }

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
