#trigger:
#  batch: true
#  branches:
#    include:
#      - refs/heads/master
#  paths:
#    exclude:
#    - README.md

pool: Computer-Vision-Team-Amsterdam

parameters:
  - name: AMLModelVersion
    displayName: Version of the OOR model in AML
    type: string
    default: 1

resources:
  repositories:
    - repository: self

variables:
  - template: variables.yaml

stages:
  - stage: Prerequisites
    displayName: "Collect all prerequisites"
    jobs:
      - template: "prerequisites-pipeline.yml"
        parameters:
          serviceConnectionName: ${{ variables.serviceConnectionName }}
          AMLModelName: ${{ variables.AMLModelName }}
          AMLModelVersion: ${{ parameters.AMLModelVersion }}
          AMLWorkspaceName: ${{ variables.AMLWorkspaceName }}
          AMLResourceGroup: ${{ variables.AMLResourceGroup }}
          AMLSubscriptionID: ${{ variables.AMLSubscriptionID }}
          downloadedModelDirectory: ${{ variables.downloadedModelDirectory }}
          publishedModelArtifactsName: ${{ variables.publishedModelArtifactsName }}

  - stage: Prebuild
    displayName: "Checks and tests prior to build"
    dependsOn: Prerequisites
    jobs:
      - template: "prebuild-pipeline.yml"

  - stage: Build_test
    displayName: "[ont] Build and publish container to ont"
    dependsOn:
      - Prerequisites
      - Prebuild
    condition: |
      and
      (
        succeeded(),
        eq( variables.dtapName, 'ont' ),
        ne( variables['Build.Reason'], 'PullRequest' )
      )
    variables:
      - name: projectVersion
        value: $[ stageDependencies.Prerequisites.GetProjectVersion.outputs['getProjectVersion.PROJECT_VERSION'] ]
    jobs:
      - template: "build-pipeline.yml"
        parameters:
          serviceConnectionName: ${{ variables.serviceConnectionName }}
          AMLModelName: ${{ variables.AMLModelName }}
          AMLModelVersion: ${{ parameters.AMLModelVersion }}
          downloadedModelDirectory: ${{ variables.downloadedModelDirectory }}
          publishedModelArtifactsName: ${{ variables.publishedModelArtifactsName }}
          containerRegistryResourceGroupName: ${{ variables.containerRegistryResourceGroupName }}
          containerRegistry: ${{ variables.containerRegistry }}
          dockerImageName: ${{ variables.dockerImageName }}
          dockerImageTag: ${{ variables.dockerImageTag }}

  - stage: Build_prd
    displayName: "[prd] Build and publish container to prd"
    dependsOn:
      - Prerequisites
      - Prebuild
    condition: |
      and
      (
        succeeded(),
        eq( variables.dtapName, 'prd' )
      )
    variables:
    - name: projectVersion
      value: $[ stageDependencies.Prerequisites.GetProjectVersion.outputs['getProjectVersion.PROJECT_VERSION'] ]
    jobs:
      - template: "build-pipeline.yml"
        parameters:
          serviceConnectionName: ${{ variables.serviceConnectionName }}
          AMLModelName: ${{ variables.AMLModelName }}
          AMLModelVersion: ${{ parameters.AMLModelVersion }}
          downloadedModelDirectory: ${{ variables.downloadedModelDirectory }}
          publishedModelArtifactsName: ${{ variables.publishedModelArtifactsName }}
          containerRegistryResourceGroupName: ${{ variables.containerRegistryResourceGroupName }}
          containerRegistry: ${{ variables.containerRegistry }}
          dockerImageName: ${{ variables.dockerImageName }}
          dockerImageTag: ${{ variables.dockerImageTag }}

  - stage: Deploy_test
    displayName: "[ont] Deploy container to ont device"
    dependsOn:
      - Build_test
    condition: |
      and
      (
        succeeded(),
        eq( variables.dtapName, 'ont' ),
        ne( variables['Build.Reason'], 'PullRequest' )
      )
    jobs:
      - template: "deploy-pipeline.yml"
        parameters:
          containerRegistry: ${{ variables.containerRegistry }}
          dockerImageName: ${{ variables.dockerImageName }}
          dockerImageTag: ${{ variables.dockerImageTag }}
