parameters:
- name: repoName
  displayName: Name of the repository to check
  type: string
- name: dependsOn
  displayName: Name of job the template depends on, if any
  type: object
  default: []
- name: pipAuditArgs
  displayName: Additional args to pass to pip-audit, e.g. to exclude certain vulnerabilities
  type: string
  default: ""


jobs:
- job: CodeQualityAndSecurity
  dependsOn: ${{ parameters.dependsOn }}
  displayName: Code quality checks and security scanning
  pool:
    vmImage: ubuntu-22.04

  steps:
  - checkout: ${{ parameters.repoName }}

  - task: CmdLine@2
    displayName: Run pre-commit hooks
    inputs:
      script: |
        pip install pre-commit==2.21.0
        pre-commit run --all-files
      workingDirectory: '$(Build.Repository.LocalPath)'

  - task: CmdLine@2
    displayName: Run Hadolint
    inputs:
      script: 'docker run --rm -i -v ${PWD}/.hadolint.yml:/bin/hadolint.yml -e XDG_CONFIG_HOME=/bin hadolint/hadolint < Dockerfile'
      workingDirectory: '$(Build.Repository.LocalPath)'
